version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    - dependency-name: "org.springframework:spring-core"
    - dependency-name: "org.springframework:spring-webmvc"
    - dependency-name: "org.springframework:spring-aop"
