# Automates creation of changelog drafts using Release Drafter
# More Info: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
name: Changelog Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Generate GitHub Release Draft
        uses: oleg-nenashev/jenkins-release-drafter@v5.2.0-jenkins-4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Generates a YAML changelog file using https://github.com/daniel-beck/jenkins-changelog-generator
      - name: Generate a YAML changelog draft
        uses: oleg-nenashev/jenkins-changelog-generator@docker
        env:
          GITHUB_AUTH: github-actions:${{ secrets.GITHUB_TOKEN }}
      - name: Upload changelog YAML to the release draft assets
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: changelog.yaml
          asset_name: changelog.yaml
          tag: untagged-${{ github.ref }}
          overwrite: true

